---
- name: Configure Home Assistant VM
  hosts: homeassistant
  become: true
  gather_facts: true

  tasks:
    - name: Ensure Home Assistant is accessible
      uri:
        url: "http://{{ ansible_host }}:8123"
        return_content: yes
        status_code: 200
        timeout: 30
      register: ha_status
      retries: 10
      delay: 30
      until: ha_status.status == 200
      ignore_errors: yes

    - name: Open firewall for Home Assistant
      ufw:
        rule: allow
        port: 8123
        proto: tcp