- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Ansible:
        - abbr: AN
          href: https://docs.ansible.com/

- Entertainment:
    - YouTube:
        - abbr: YT
          href: https://youtube.com/