include:
  - docker-compose.yml
  - immich/docker-compose.yml
  - tubearchivist/docker-compose.yml
  - matomo/docker-compose.yml
  - hermes-agent/docker-compose.yml
  - archivebox/docker-compose.yml
  - path: penpot/docker-compose.yml
    env_file: penpot/.env
