global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s

  # Alloy metrics
  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
    scrape_interval: 15s

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 15s

  # Loki metrics
  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']
    scrape_interval: 15s

  # Node exporter (if you add it later)
  - job_name: 'node-exporter'
    static_configs:
      - targets: []  # Add node-exporter:9100 when deployed
    scrape_interval: 15s

  # Docker daemon metrics (if enabled)
  - job_name: 'docker'
    static_configs:
      - targets: []  # Add docker host if metrics enabled
    scrape_interval: 30s